package biliutil

import (
	"bytes"
	"fmt"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type CookieWriteOptions struct {
	Dir      string
	UID      int64
	Usage    string
	Now      func() time.Time
	FileMode fs.FileMode
}

type CookieWriteResult struct {
	Path      string    `json:"path"`
	UID       int64     `json:"uid"`
	ExpiresAt time.Time `json:"expires_at"`
	Names     []string  `json:"names"`
}

type netscapeCookieLine struct {
	Domain            string
	IncludeSubdomains string
	Path              string
	Secure            string
	Expiry            int64
	Name              string
	Value             string
	HttpOnly          bool
}

func WriteNetscapeCookieFile(cookies []*http.Cookie, opts CookieWriteOptions) (CookieWriteResult, error) {
	now := time.Now()
	if opts.Now != nil {
		now = opts.Now()
	}
	mode := opts.FileMode
	if mode == 0 {
		mode = 0o600
	}
	dir := opts.Dir
	if dir == "" {
		dir = filepath.Join(".cookies", "bilibili")
	}
	usage := strings.TrimSpace(opts.Usage)
	if usage == "" {
		usage = "download"
	}

	content, expiresAt, names, err := FormatNetscapeCookies(cookies, now)
	if err != nil {
		return CookieWriteResult{}, err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return CookieWriteResult{}, fmt.Errorf("create cookie dir: %w", err)
	}

	fileName := fmt.Sprintf("bili_%d_%s.txt", opts.UID, sanitizeCookieUsage(usage))
	path := filepath.Join(dir, fileName)
	tmpPath := filepath.Join(dir, "."+fileName+".tmp")

	// 写入内容（可能加密）
	writeContent, err := encryptCookieFile(content)
	if err != nil {
		return CookieWriteResult{}, fmt.Errorf("encrypt cookie file: %w", err)
	}
	if err := os.WriteFile(tmpPath, writeContent, mode); err != nil {
		return CookieWriteResult{}, fmt.Errorf("write cookie file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return CookieWriteResult{}, fmt.Errorf("replace cookie file: %w", err)
	}
	return CookieWriteResult{
		Path:      path,
		UID:       opts.UID,
		ExpiresAt: expiresAt,
		Names:     names,
	}, nil
}

func FormatNetscapeCookies(cookies []*http.Cookie, now time.Time) ([]byte, time.Time, []string, error) {
	lines := make([]netscapeCookieLine, 0, len(cookies))
	seen := map[string]bool{}
	names := make([]string, 0, len(cookies))
	required := map[string]bool{
		"SESSDATA":   false,
		"bili_jct":   false,
		"DedeUserID": false,
	}
	expiresAt := time.Time{}

	for _, cookie := range cookies {
		line, ok := NormalizeBiliCookie(cookie, now)
		if !ok {
			continue
		}
		lines = append(lines, line)
		if !seen[line.Name] {
			seen[line.Name] = true
			names = append(names, line.Name)
		}
		if _, ok := required[line.Name]; ok {
			required[line.Name] = true
		}
		if line.Name == "SESSDATA" {
			expiresAt = time.Unix(line.Expiry, 0)
		}
	}
	for _, ok := range required {
		if !ok {
			return nil, time.Time{}, nil, ErrCookieMissing
		}
	}
	if expiresAt.IsZero() {
		expiresAt = now.Add(30 * 24 * time.Hour)
	}

	sort.SliceStable(lines, func(i, j int) bool {
		return lines[i].Name < lines[j].Name
	})
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteString("# Netscape HTTP Cookie File\n")
	buf.WriteString("# This file is generated by hikami-go. Do not commit it.\n")
	for _, line := range lines {
		domain := line.Domain
		if line.HttpOnly {
			domain = "#HttpOnly_" + domain
		}
		fmt.Fprintf(
			&buf,
			"%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			domain,
			line.IncludeSubdomains,
			line.Path,
			line.Secure,
			line.Expiry,
			line.Name,
			line.Value,
		)
	}
	return buf.Bytes(), expiresAt, names, nil
}

func NormalizeBiliCookie(cookie *http.Cookie, now time.Time) (netscapeCookieLine, bool) {
	if cookie == nil || strings.TrimSpace(cookie.Name) == "" {
		return netscapeCookieLine{}, false
	}
	domain := cookie.Domain
	if domain == "" {
		domain = ".bilibili.com"
	}
	path := cookie.Path
	if path == "" {
		path = "/"
	}
	expires := cookie.Expires
	if expires.IsZero() {
		expires = now.Add(30 * 24 * time.Hour)
	}
	includeSubdomains := "FALSE"
	if strings.HasPrefix(domain, ".") {
		includeSubdomains = "TRUE"
	}
	secure := "FALSE"
	if cookie.Secure {
		secure = "TRUE"
	}
	return netscapeCookieLine{
		Domain:            domain,
		IncludeSubdomains: includeSubdomains,
		Path:              path,
		Secure:            secure,
		Expiry:            expires.Unix(),
		Name:              cookie.Name,
		Value:             cookie.Value,
		HttpOnly:          cookie.HttpOnly,
	}, true
}

func sanitizeCookieUsage(value string) string {
	var b strings.Builder
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "download"
	}
	return b.String()
}
